version: 0.2

env:
  parameter-store:
    DEMO_REPO_URL: "demo_repo_url"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION
      - DEMOONE_REPOSITORY_URI=DEMO_REPO_URL/demo-service-one
      - DEMOTWO_REPOSITORY_URI=DEMO_REPO_URL/demo-service-two
      - DEMOTHREE_REPOSITORY_URI=DEMO_REPO_URL/demo-service-three
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - ONE_IMAGE_TAG=demo-service-one-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - TWO_IMAGE_TAG=demo-service-two-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - THREE_IMAGE_TAG=demo-service-three-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo Image id is $ONE_IMAGE_TAG, $TWO_IMAGE_TAG, $THREE_IMAGE_TAG
  build:
    commands:
      - echo Build started for demo-service-one
      - echo Building the Docker image...
      - cd skill-tracker-service
      - ls -a
      - docker-compose build
      - docker images     
      - docker image tag demo-service-one $DEMOONE_REPOSITORY_URI:$ONE_IMAGE_TAG
      - docker image tag demo-service-one $DEMOONE_REPOSITORY_URI:latest
      
      - docker image tag demo-service-two $DEMOTWO_REPOSITORY_URI:$TWO_IMAGE_TAG
      - docker image tag demo-service-two $DEMOTWO_REPOSITORY_URI:latest
      
      - docker image tag demo-service-three $DEMOTHREE_REPOSITORY_URI:$THREE_IMAGE_TAG
      - docker image tag demo-service-three $DEMOTHREE_REPOSITORY_URI:latest
      
      

      - docker image ls
      - echo Tagging completed
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Pushing docker images into
      - echo $(aws ecr get-login-password)|docker login --password-stdin --username AWS DEMO_REPO_URL

      - docker push $DEMOONE_REPOSITORY_URI:$ONE_IMAGE_TAG
      - docker push $DEMOONE_REPOSITORY_URI:latest

      - docker push $DEMOTWO_REPOSITORY_URI:$TWO_IMAGE_TAG
      - docker push $DEMOTWO_REPOSITORY_URI:latest

      - docker push $DEMOTHREE_REPOSITORY_URI:$THREE_IMAGE_TAG
      - docker push $DEMOTHREE_REPOSITORY_URI:latest
     

      - docker image ls
      - echo Writing image definitions file...
      - printf '[{"name":"demotwo","imageUri":"%s"}]' $DEMOTWO_REPOSITORY_URI:$TWO_IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
    