version: "3"
services:
  demo-service-one:
    container_name: demo-service-one
    build:
      context: demo-service-one
      dockerfile: Dockerfile
      args:
        - dirname=demo-service-one
    image: demo-service-one
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    ports:
        - 8080:8080
  demo-service-two:
    container_name: demo-service-two
    build:
      context: demo-service-two
      dockerfile: Dockerfile
      args:
        - dirname=demo-service-two
    image: demo-service-two
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    ports:
        - 8081:8081 
  demo-service-three:
    container_name: demo-service-three
    build:
      context: demo-service-three
      dockerfile: Dockerfile
      args:
        - dirname=demo-service-three
    image: demo-service-three
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    ports:
        - 8082:8082