Type: AWS::CodeBuild::Project
Properties: 
  Artifacts: 
    Artifacts
  BadgeEnabled: Boolean
  BuildBatchConfig: 
    ProjectBuildBatchConfig
  Cache: 
    ProjectCache
  ConcurrentBuildLimit: Integer
  Description: String
  EncryptionKey: String
  Environment: 
    Environment
  FileSystemLocations: 
    - ProjectFileSystemLocation
  LogsConfig: 
    LogsConfig
  Name: String
  QueuedTimeoutInMinutes: Integer
  ResourceAccessRole: String
  SecondaryArtifacts: 
    - Artifacts
  SecondarySources: 
    - Source
  SecondarySourceVersions: 
    - ProjectSourceVersion
  ServiceRole: String
  Source: 
    Source
  SourceVersion: String
  Tags: 
    - Tag
  TimeoutInMinutes: Integer
  Triggers: 
    ProjectTriggers
  Visibility: String
  VpcConfig: 
    VpcConfig
